"""empty message

Revision ID: 23faff93799d
Revises: 
Create Date: 2021-07-17 22:43:01.791231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23faff93799d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professor'))
    )
    op.create_table('test_room',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('block_list', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name=op.f('fk_test_room_professor_id_professor'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_room'))
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_room_id', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['test_room_id'], ['test_room.id'], name=op.f('fk_student_test_room_id_test_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_room_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_log_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_room_id'], ['test_room.id'], name=op.f('fk_log_test_room_id_test_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('student')
    op.drop_table('test_room')
    op.drop_table('professor')
    # ### end Alembic commands ###
