"""empty message

Revision ID: 4431291f0ee4
Revises: 0a9c5dfde792
Create Date: 2021-07-18 01:32:05.926235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4431291f0ee4'
down_revision = '0a9c5dfde792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_student')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('test_room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('test_room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('_alembic_tmp_student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_room_id', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['test_room_id'], ['test_room.id'], name='fk_student_test_room_id_test_room', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_student')
    )
    # ### end Alembic commands ###
