"""empty message

Revision ID: 6acd7bdc2a12
Revises: e99123c82216
Create Date: 2021-07-18 02:21:48.296990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acd7bdc2a12'
down_revision = 'e99123c82216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('test_room_id', sa.String(), nullable=False),
    sa.Column('student_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['student_index'], ['student.index'], name=op.f('fk_log_student_index_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_room_id'], ['test_room.id'], name=op.f('fk_log_test_room_id_test_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index', name=op.f('pk_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
