"""empty message

Revision ID: bab28d93d304
Revises: 6acd7bdc2a12
Create Date: 2021-07-18 02:24:35.926925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab28d93d304'
down_revision = '6acd7bdc2a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_log_test_room_id_test_room', type_='foreignkey')
        batch_op.drop_column('test_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_room_id', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('fk_log_test_room_id_test_room', 'test_room', ['test_room_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
