"""empty message

Revision ID: fc47cc2b1cda
Revises: ae4651fccb72
Create Date: 2021-07-18 01:56:33.596568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc47cc2b1cda'
down_revision = 'ae4651fccb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
