"""empty message

Revision ID: 5f20f3b91c96
Revises: d3492caa9bb8
Create Date: 2021-08-14 11:53:06.040112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f20f3b91c96'
down_revision = 'd3492caa9bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_room', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
