"""empty message

Revision ID: 68ee37e507e5
Revises: 23faff93799d
Create Date: 2021-07-18 00:17:59.684397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ee37e507e5'
down_revision = '23faff93799d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('test_room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('test_room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
