"""empty message

Revision ID: 91dda4785b43
Revises: 1bd0e411ad2c
Create Date: 2021-07-10 13:18:43.199348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dda4785b43'
down_revision = '1bd0e411ad2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_professor_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_professor_username'), type_='unique')

    # ### end Alembic commands ###
